[package]
name = "ef-tests"
version.workspace = true
description = "EF testing support for reth."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
ef-tests = []
asm-keccak = ["reth-primitives/asm-keccak"]

[dependencies]
reth-primitives.workspace = true
reth-db = { workspace = true, features = ["mdbx", "test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-stages.workspace = true
reth-interfaces.workspace = true
reth-revm.workspace = true
reth-node-ethereum.workspace = true
reth-rpc-types-compat.workspace = true
reth-rpc-types.workspace = true
reth-rpc.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-network-api.workspace = true
reth-tasks = { workspace = true }

alloy-rlp.workspace = true
tokio = "1.28.1"
walkdir = "2.3.3"
serde = "1.0.163"
serde_json.workspace = true
thiserror.workspace = true
rayon.workspace = true

# raiko
raiko-host.workspace = true
raiko-lib.workspace = true
raiko-primitives.workspace = true
anyhow.workspace = true
